apps/chat/urls.py
from django.urls import path

from . import views


app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from apps.common.views import HealthView
from .api import api

urlpatterns = [
    path("admin/", admin.site.urls),
    path('chat/', include('apps.chat.urls')),

    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("dash/", TemplateView.as_view(template_name="dash.html"), name="dash"),
    path("team/", TemplateView.as_view(template_name="team.html"), name="team"),
    path("stats", HealthView.as_view(), name="stats"),
    path("vite/", TemplateView.as_view(template_name="vite.html"), name="vite"),
    path("ht/", include("health_check.urls")),
    path("api/", api.urls),
]

apps/chat/models.py
from django.db import models

# Create your models here.

apps/chat/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'chat/index.html')


def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name': room_name
    })

apps/common/views.py
import re

from django.http import HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView

from health_check.mixins import CheckMixin


class MediaType:
    """
    Sortable object representing HTTP's accept header.
    .. seealso:: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept
    """

    pattern = re.compile(
        r"""
          ^
          (?P<mime_type>
            (\w+|\*)                      # Media type, or wildcard
            /
            ([\w\d\-+.]+|\*)              # subtype, or wildcard
          )
          (
            \s*;\s*                       # parameter separator with optional whitespace
            q=                            # q is expected to be the first parameter, by RFC2616
            (?P<weight>
              1([.]0{1,3})?               # 1 with up to three digits of precision
              |
              0([.]\d{1,3})?              # 0.000 to 0.999 with optional precision
            )
          )?
          (
            \s*;\s*                       # parameter separator with optional whitespace
            [-!#$%&'*+.^_`|~0-9a-zA-Z]+   # any token from legal characters
            =
            [-!#$%&'*+.^_`|~0-9a-zA-Z]+   # any value from legal characters
          )*
          $
        """, re.VERBOSE)

    def __init__(self, mime_type, weight=1.0):
        self.mime_type = mime_type
        self.weight = float(weight)

    @classmethod
    def from_string(cls, value):
        """Return single instance parsed from given accept header string."""
        match = cls.pattern.search(value)
        if match is None:
            raise ValueError('"%s" is not a valid media type' % value)
        try:
            return cls(match.group('mime_type'), float(match.group('weight') or 1))
        except ValueError:
            return cls(value)

    @classmethod
    def parse_header(cls, value='*/*'):
        """Parse HTTP accept header and return instances sorted by weight."""
        yield from sorted((
            cls.from_string(token.strip())
            for token in value.split(',')
            if token.strip()
        ), reverse=True)

    def __str__(self):
        return "%s; q=%s" % (self.mime_type, self.weight)

    def __repr__(self):
        return "%s: %s" % (type(self).__name__, self.__str__())

    def __eq__(self, other):
        return self.weight == other.weight and self.mime_type == other.mime_type

    def __lt__(self, other):
        return self.weight.__lt__(other.weight)


class HealthView(CheckMixin, TemplateView):
    template_name = 'stats.html'

    @method_decorator(never_cache)
    def get(self, request, *args, **kwargs):
        status_code = 500 if self.errors else 200

        format_override = request.GET.get('format')

        if format_override == 'json':
            return self.render_to_response_json(self.plugins, status_code)

        accept_header = request.META.get('HTTP_ACCEPT', '*/*')
        for media in MediaType.parse_header(accept_header):
            if media.mime_type in ('text/html', 'application/xhtml+xml', 'text/*', '*/*'):
                context = self.get_context_data(**kwargs)
                return self.render_to_response(context, status=status_code)
            elif media.mime_type in ('application/json', 'application/*'):
                return self.render_to_response_json(self.plugins, status_code)
        return HttpResponse(
            'Not Acceptable: Supported content types: text/html, application/json',
            status=406,
            content_type='text/plain',
        )

    def get_context_data(self, **kwargs):
        return {**super().get_context_data(**kwargs), "plugins": self.plugins}

    def render_to_response_json(self, plugins, status):
        return JsonResponse(
            {str(p.identifier()): str(p.pretty_status()) for p in plugins},
            status=status
        )

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
{% get_current_language as language_code %}

<html lang="{{ language_code }}">

<head>
  <title>{% spaceless %}{% block title %}Home{% endblock %}{% endspaceless %} </title>
  <meta charset="UTF-8">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {# site meta and seo meta tags, override on specific pages as necessary. #}
  {% block site_meta %}{% endblock %}
  {% block seo-meta %}
    <meta name="robots" content="index,follow">
  {% endblock %}


  {# optional #}
  <link href="https://cdn.jsdelivr.net/npm/daisyui@1.16.2/dist/full.css" rel="stylesheet" type="text/css" />
  <link href="{% static 'output.css' %}" rel="stylesheet" type="text/css" />
  {% block extra_css %}{% endblock %}
  {% block head_js %}{% endblock %}

</head>

<body>
<div>
  <div class="flex h-screen antialiased overflow-x-hidden bg-base-200 text-base-content">

    <div class="{% block page_wrapper_class %}h-full w-full overflow-hidden fixed{% endblock %}">
      {# content goes here #}
      {% block content %}{% endblock %}


    </div>
  </div>
</div>
{% block footer_js %}

  <script type="text/javascript" src="{% static 'js/cookie.js' %}"></script>
  <script src="https://unpkg.com/swagger-client"></script>
  <script>
    // Cookie func
    const csrftoken = getCookie('csrftoken');
    const authHeaders = {'X-CSRFToken': csrftoken}

    // the application uses the swagger js client to interact with the api
    // if you are building a separate frontend, consult the docs on how to generate a client in typescript
    const client = SwaggerClient('/api/openapi.json', {
      requestInterceptor: (req) => {
        req.headers['X-CSRFToken'] = csrftoken;
        req.headers['Content-Type'] = 'application/json';
        return req;
      },
    })
    window.client = client;

    //uncomment to log api endpoints to console for debugging purposes
    //client.then(client => console.log(client.apis))

   
  </script>

{% endblock %}

</body>
</html>

templates/chat/_chat_message.html
<li  :id='`msg_${msg.id}`' class="flex p-2 rounded" :class="data.userID === msg.userId ? 'justify-end' : 'justify-start'" x-transition.duration.1200ms>
    <div class="flex space-x-3 w-1/3 bg-gray-100 rounded-lg px-3 py-2" :class="data.userID === msg.userId ? 'flex-row-reverse' : ''">
      <div class="flex-shrink-0">
        <img class="h-8 w-8 rounded-full inline-block" :src="msg.avatarUrl" alt="">
      </div>
      <div>
        <div class="text-sm">
          <p href="#" class="text-xs font-bold text-gray-600" x-text="msg.userId"></p>
        </div>
        <div class="mt-1 text-sm text-gray-900">
          <p x-text="msg.message"></p>
        </div>
        <div class="mt-1 text-xs space-x-2">
          <span class="text-gray-500 text-xs" x-text="getDate(msg.date)"></span>
          <span class="text-gray-500 text-xs">&middot;</span>
          <button type="button" class="text-gray-900 text-xs" @click="copyToText(msg.message, msg.from)">Quote</button>
        </div>
      </div>
    </div>
</li>

templates/chat/_text_area.html
<div class="flex items-start space-x-4">
    <div class="min-w-0 flex-1">
        <div class="focus-within:border-indigo-600 w-full">
          <label for="comment" class="sr-only">Add a post..</label>
          <textarea x-model="data.message" rows="2" name="comment" id="comment" class="textarea w-full resize-none rounded-md shadow" placeholder="Add a post..."></textarea>
        </div>
        <div class="pt-2 flex justify-between">
          <div class="flex items-center space-x-5">
            <div class="flow-root">
              <button @click="clearStorage()" type="button" class="-m-2 w-10 h-10 rounded-full inline-flex items-center justify-center text-gray-400 hover:text-gray-500">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                  </svg>
                <span class="sr-only">Clear</span>
              </button>
            </div>
          </div>
          <div class="flex-shrink-0">
            <button @click="sendMessage()" type="submit" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
              Post
            </button>
          </div>
        </div>

    </div>
  </div>
  

templates/chat/index.html
<!--Alpine , WS, Django -->
{% extends 'base.html' %}{% load static %} {% block head_js %}

<script defer src="https://unpkg.com/@alpinejs/persist@3.x.x/dist/cdn.min.js"></script>
<script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>

{% endblock %} {% block content %}
{% include "components/nav.html" with btn_text="connect" %}

<div class=" container px-4  mx-auto pt-12 flex justify-between items-center px-4 py-8  xl:px-10" x-data="chatIndex">
    <div class="flex flex-col w-full max-w-sm md:max-w-3xl">
        <!--Room selector -->
        <div class="flex flex-row justify-between mb-5">
            <h1 class="text-2xl font-bold px-2">Public Chat Rooms</h1>

            <select x-on:change="data.roomInput = data.roomInputSelect" x-model="data.roomInputSelect" class="select select-bordered w-full max-w-xs" placeholder="select chat room">
                <option disabled value="">Your past chat rooms</option>
                <template x-for="(room, i) in data.rooms">
                    <option x-text="room"></option>
                </template>
            </select>
        </div>
        <!--Room input -->
        <section class="flex flex-col space-y-4 w-full max-w-sm md:max-w-5xl p-2">
            <p>Create a new room?</p>
            <input class="input" x-model="data.roomInput" type="text" size="100" />
            <div class="flex flex-row">
                <button :disabled="data.roomInput == ''" type="button" @click="goToRoom()"
                    class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white  focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    :class="data.roomInput == '' ? 'bg-gray-100 text-gray-900' : 'bg-indigo-600 hover:bg-indigo-700'">Open
                    Room</button>

                    <button @click="clearStorage()" type="button" class=" w-10 h-10 rounded-full inline-flex items-center justify-center text-gray-400 hover:text-gray-500">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="red">
                            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                          </svg>
                        <span class="sr-only">Clear</span>
                      </button>
            </div>

        </section>
    </div>
</div>

{% endblock %}
{% block footer_js %}

<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('chatIndex', function () {
            return {
                data: {
                    roomInput:'',
                    roomInputSelect:'',
                    rooms: this.$persist([])
                },
                goToRoom() {
                    //return if empty
                    if(this.data.roomInput == ''){console.log(this.data.roomInput); return};

                    // push room to storage and navigate
                    this.data.rooms.push(this.data.roomInput);
                    window.location.pathname = '/chat/' + this.data.roomInput + '/';
                },
                clearStorage() {
                    this.data.messages = []
                    window.sessionStorage.removeItem(`${rooms}`)
                }

            }

        })
    })
</script>
{% endblock %}

templates/chat/room.html
<!--Alpine , WS, Django -->
{% extends 'base.html' %}{% load static %}
{% block head_js %}
    <script defer src="https://unpkg.com/@alpinejs/persist@3.x.x/dist/cdn.min.js"></script>
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    
{% endblock %}
{% block content %}
    {% include "components/nav.html" with btn_text="connect" %}
    <div class="container mx-auto pt-12 flex justify-between items-center py-8 px-4 xl:px-10" x-data="chatRoom">
        <div class="flex flex-col w-full max-w-sm md:max-w-3xl" >
            <h1 class="text-2xl font-bold px-2" x-text='`Room: ${data.roomName}`'></h1>
            <section class="flex flex-col w-full max-w-sm md:max-w-5xl p-2 relative">
                <div class="absolute inset-1/2" x-show="isLoading">
                    <div class="rounded-full animate-bounce">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                          </svg>
                    </div>
                </div>
         
              <div id="chatContent" class="border-2 border-gray-200 rounded-lg w-full mb-5 h-96 min-h-full overflow-y-auto flex flex-col" :class="isLoading && 'blur-lg'">
                <ul role="list" class="space-y-2 flex flex-col overflow-x-hidden">
                    <template x-for="(msg, index) in data.messages">
                        {% include "chat/_chat_message.html" %}
                    </template>
                </ul>
              </div>
             {% include "chat/_text_area.html" %}
            </section>
        </div>    
    </div>
    
{% endblock %}
{% block footer_js %}
{{ room_name|json_script:"room-name" }}

<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
<script src="{% static 'js/timeago.min.js'%}"></script>
<script>

    const roomName = JSON.parse(document.getElementById('room-name').textContent);
    const uniqueID = function () {
        return '_' + Math.random().toString(36).substr(2, 9);
    }
    let chatSocket;

    document.addEventListener('alpine:init', () => {
        Alpine.data('chatRoom', function () {
            return {
                isLoading: true,
                data:{
                    message: "",
                    roomName: roomName,
                    messages: this.$persist([]).using(sessionStorage).as(`${roomName}-messages`), // persist in localstorge
                    userID: this.$persist(uniqueID()), // persist in localstorge,
                    
                },
                init(){
                    console.log("connecting")
                    this.connect();
                    this.$nextTick(()=> this.scrollLastMessageIntoView());
                    console.log(timeago.format(new Date(1640721812850)))
                    
                },
                getDate(date){
                    console.log(date, timeago.format(date))
                    return timeago.format(parseInt(date))
                },
                connect(){
                    var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";

                    chatSocket = new ReconnectingWebSocket(
                        ws_scheme
                        + '://'
                        + window.location.host
                        + '/ws/chat/'
                        + roomName
                        + '/'
                    );
                    this.chatListeners()
                   
                },
                copyToText(msg, from){
                    this.data.message = `@${from} - ${msg} \n`
                    
                },
                scrollLastMessageIntoView(){
                    if(this.data.messages.length > 0){
                        let lastMessageId = `msg_${this.data.messages[this.data.messages.length - 1].id}`;
                        console.log(lastMessageId)
                        let el = document.getElementById(lastMessageId)
                        if (el) {
                            el.scrollIntoView({ behavior: "smooth", block: "end" })
                        }
                    }
                    if (this.isLoading){this.isLoading = false}
                    
                },
                sendMessage(){
                    let data = {
                        'from': this.data.message,
                        'date': new Date().getTime(),
                        'timesince':'',
                        'message': this.data.message,
                        'userId': this.data.userID,
                        'id':uniqueID(),
                        'avatarUrl': `https://i.pravatar.cc/150?u=${this.data.userID}`,
                    }
                    
                    chatSocket.send(JSON.stringify(data)); //send string data
                    this.data.message = ''
                },
                receiveMessage(e){
                    console.log("chatSocket.onmessage", e)
                    const data = JSON.parse(e.data)
                    this.data.messages.push(data)
                    let id = `msg_${data.id}`
                    this.$nextTick(()=>this.scrollLastMessageIntoView()) // wait for dom to render element.
                    
                },
                chatListeners(){
                    chatSocket.onmessage = (e) => this.receiveMessage(e)
                    chatSocket.onclose = (e)=> console.log("chatSocket.onclose", e)
                    chatSocket.onerror = (e) => console.log("chatSocket.onerror", e)
                },
                clearStorage(){
                    this.data.messages = []
                    window.sessionStorage.removeItem(`${roomName}-messages`)
                }

            }

        })
    })

</script>
{% endblock %}

templates/components/header.html
{% load static %}
<section class="pb-20">
  <div class="container px-4 mx-auto pt-12">
    <div class="flex flex-wrap items-center -mx-4">
      <div class="w-full md:w-1/2 px-4 mb-6 md:mb-0">
        <span class="font-semibold text-xs text-blue-400">TailwindCSS & DaisyUI (Optional)</span>
        <h2 class="mt-8 mb-6 lg:mb-12 text-4xl lg:text-5xl font-semibold">Django, Vitejs + React Starter</h2>
        <div class="max-w-lg mb-6 lg:mb-12">
          <p class="text-xl text-gray-500">Simple Starter</p>
        </div>
        <div class="flex flex-wrap">
            <a class="btn btn-primary" href="/vite">Demo</a>
            <a class="btn btn-secondary btn-outline ml-2" href="#">Learn More</a></div>
      </div>
      <div class="relative w-full md:w-1/2 px-4">
        <img class="hidden lg:block top-0 right-0 z-10 lg:mt-28" src="{% static 'images/landing.svg' %}" alt="">
      </div>
    </div>
  </div>
</section>

templates/components/logo.html
<a class="flex-shrink-0 text-2xl font-semibold" href="{% url 'home' %}">
      <span class="shadow-xl text-primary"><svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM7 9a1 1 0 100-2 1 1 0 000 2zm7-1a1 1 0 11-2 0 1 1 0 012 0zm-.464 5.535a1 1 0 10-1.415-1.414 3 3 0 01-4.242 0 1 1 0 00-1.415 1.414 5 5 0 007.072 0z" clip-rule="evenodd" />
            </svg>
      <span>
</a>

templates/components/nav.html
<nav class="container px-4 mx-auto pt-12 flex justify-between items-center py-8 px-4 xl:px-10">
  <div class="flex flex-row">
    {% include "components/logo.html" %}
    <span class="text-2xl font-semibold mt-2 ml-3">Advantch Tutorials</span>
  </div>
  <div class="lg:hidden">
    <button
      class="navbar-burger flex items-center p-3 hover:bg-gray-50 rounded"
    >
      <svg
        class="block h-4 w-4"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
        <title>Mobile menu</title>
        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
      </svg>
    </button>
  </div>
  <ul class="hidden lg:flex lg:ml-auto lg:mr-12 lg:items-center lg:w-auto lg:space-x-12">
    <li><a class="text-sm font-medium" href="{% url 'stats' %}">Server Stats</a></li>
    <li><a class="text-sm font-medium" href="{% url 'chat:index' %}">Public Chat Room</a></li>
  </ul>
  <div class="hidden lg:block">
    <a class="btn btn-sm btn-secondary" href="#">{{btn_text}}</a>
  </div>
</nav>

<!--mobile nav-->
<div class="hidden navbar-menu fixed top-0 left-0 bottom-0 w-5/6 max-w-sm z-50">
    <div class="navbar-backdrop fixed inset-0 bg-gray-800 opacity-25"></div>
    <nav class="relative flex flex-col py-6 px-6 w-full h-full bg-white border-r overflow-y-auto">
      <div class="flex items-center mb-8">
        {% include "components/logo.html" %}
        <button class="navbar-close">
          <svg class="h-6 w-6 text-gray-500 cursor-pointer hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </button>
      </div>
      <div>
        <ul>
          <li class="mb-1"><a class="block p-4 text-sm font-medium text-gray-900 hover:bg-gray-50 rounded" href="#">About</a></li>
          <li class="mb-1"><a class="block p-4 text-sm font-medium text-gray-900 hover:bg-gray-50 rounded" href="#">Company</a></li>
        </ul>
      </div>
      <div class="mt-auto">
        <div class="pt-6"><a class="block py-3 text-center text-sm leading-normal bg-red-50 hover:bg-red-100 text-red-300 font-semibold rounded transition duration-200" href="#">Login</a></div>
        <p class="mt-6 mb-4 text-sm text-center text-gray-500">
          <span>© 2021 All rights reserved.</span>
        </p>
      </div>
    </nav>
  </div>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% include "components/nav.html" with btn_text="connect" %}
    {% include "components/header.html" %}
{% endblock %}

templates/stats.html
{% extends 'base.html' %}{% load static %}

{% block content %}
    {% include "components/nav.html" with btn_text="connect" %}
    <div class="container px-4 mx-auto pt-12 flex justify-between items-center py-8 px-4 xl:px-10">
        
        <div class="flex flex-col">
            <div class="flex mb-10">
                    <h2 class="fontbold text-primary text-xs">Database: </h2> 
                    <p class="text-xs">{{database}}</p>
            </div>   
            <div class="flex mb-2">
                <h2 class="fontbold text-primary text-xs">Server Stats</h2> 
             </div>   
            <div class="grid grid-cols-3 gap-4">
                {% for plugin in plugins %}
                <div class="card rounded-sm bg-gray-100 shadow-lg min-w-xs max-w-xs">
                    <div class="card-body">
                        <h2 class="card-title text-xs">{{ plugin.identifier }}</h2> 
                        <p class="text-xs text-success animate-pulse">{{ plugin.pretty_status }}</p>
                        <p class="text-xs fontbold">{{ plugin.time_taken|floatformat:4 }} seconds</p>
                    </div>
                </div>
               {% endfor %}
            </div>
        </div>
        
        
    </div>
    
{% endblock %}

templates/vite.html
   
{% extends 'base.html' %}{% load django_vite %}
{% block title %}Vite React Echarts Example{% endblock %}
{% block head_js %}
    {% vite_hmr_client %}
{% endblock %}
{% block content %}
      {% include "components/nav.html" with btn_text="connected" %}
      <section class="container mx-auto pt-12 py-8 px-4 lg:px-6 xl:px-12">
        <div class="flex flex-row p-10">
            <div id="chart-container" class="w-full md:w-1/2 h-96"></div
            <div id="controls-container" class="w-full md:w-1/2 h-96"></div
        </div>
      </section>
{% endblock %}
{% block footer_js %}
    {% vite_asset 'js/main.jsx' %}
    {{block.super}}
{% endblock %}